defaults: &defaults
  serviceName: image-handler
  offlinePort: 80
  region: 'us-east-1'
  environment: &defaults.environment
    DEFAULT_QUALITY: 75
    DEFAULT_COMPRESS_QUALITY: 45
    SLS_IGNORE: favicon.ico
    SLS_VALID_PATH_REGEX: '.*'
    MAX_IMAGE_WIDTH: 2000
    MAX_IMAGE_HEIGHT: 1000
    PNGQUANT_SPEED: 10
    DEFAULT_CACHE_CONTROL: 'max-age=2592000'

stages:
  production:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SECURITY_KEY: ''
      SOURCE_BUCKET: 'assets.servicepartner.one'
      CUSTOM_DOMAIN: 'images.sqoneapi.com'
  staging:
    <<: *defaults
    environment:
      <<: *defaults.environment
      SOURCE_BUCKET: 'assets-dev.servicepartner.one'
      SECURITY_KEY: ''
      CUSTOM_DOMAIN: 'staging-images.sqoneapi.com'